# Generated by Django 5.1.2 on 2024-10-15 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('time', models.TimeField(max_length=15, verbose_name='Время, когда необходимо выполнять привычку')),
                ('action', models.CharField(max_length=100, verbose_name='Действие, которое представляет собой привычка')),
                ('pleasant_habit', models.BooleanField(default=False, verbose_name='Является ли привычка приятной')),
                ('periodicity', models.IntegerField(default=1, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.IntegerField(default=120, verbose_name='Время на выполнение')),
                ('publicity', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('linked_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
